import random
import importlib
import inspect
import json # <-- Import json
import os   # <-- Import os
from pathlib import Path
import numpy as np
from gymnasium import Env, spaces

# ─── constants ──────────────────────────────────────────────
H, W = 30, 30                       # fixed board size
N_COLORS = 10                       # palette 0-9
MAX_TRAIN_PAIRS = 5                 # Max original train pairs to include in obs
TOTAL_CHANNELS = 1 + 2 * MAX_TRAIN_PAIRS # 1 current_state + N train_inputs + N train_outputs
PAD_VALUE = -2                      # A value distinct from colors (0-9) and unpainted (-1)

# ─── Paths and Data Loading ─────────────────────────────────
# !!! IMPORTANT: Set this path to your ARC training data directory !!!
ARC_DATA_DIR = Path("./data/training")
assert ARC_DATA_DIR.is_dir(), f"ARC training data not found at: {ARC_DATA_DIR}"
# Load original ARC task filenames (assuming they are the base for generators)
ORIGINAL_ARC_TASKS = {f.stem: f for f in ARC_DATA_DIR.glob("*.json")}


# ─── import RE-ARC generators ───────────────────────────────
RE_ARC_DIR = Path(__file__).parent / "re-arc"
# Filter TASK_IDS to only those with BOTH a generator AND an original task file
TASK_IDS = sorted([
    fn.split("_", 1)[1] for fn in dir(importlib.import_module("re-arc.generators"))
    if fn.startswith("generate_") and fn.split("_", 1)[1] in ORIGINAL_ARC_TASKS
])
assert TASK_IDS, "No common Task IDs found between re-arc generators and ARC_DATA_DIR"
generators = importlib.import_module("re-arc.generators")

# ─── Grid Padding Utility ───────────────────────────────────
def pad_grid(grid, target_shape=(H, W), fill=0):
    """Pads/crops a grid to the target shape."""
    # Ensure grid is numpy array
    grid_np = np.array(grid, dtype=np.int8)
    h, w = grid_np.shape
    # Use the specified fill value
    g = np.full(target_shape, fill, dtype=np.int8)
    # Calculate bounds to prevent overflow
    h_slice = min(h, target_shape[0])
    w_slice = min(w, target_shape[1])
    # Copy the relevant part
    g[:h_slice, :w_slice] = grid_np[:h_slice, :w_slice]
    return g

# ─── environment ────────────────────────────────────────────
class ARCPuzzleEnv(Env):
    """
    Autoregressive painting with few-shot examples in observation:
        • Action = (row, col, color)
        • Observation = current canvas ⊕ generated input ⊕ original train examples (flattened multi-channel)
        • Episode ends after H×W steps
    """
    metadata = {"render_modes": []}

    def __init__(self, seed: int | None = None):
        super().__init__()
        self.rng = random.Random(seed)

        # action space: choose row, column, colour
        self.action_space = spaces.MultiDiscrete([H, W, N_COLORS])

        # observation space: Flattened multi-channel grid
        # Channels: [current_state, train_in_1, ..., train_in_N, train_out_1, ..., train_out_N]
        # Using PAD_VALUE as lower bound, N_COLORS-1 as upper
        obs_shape_flat = TOTAL_CHANNELS * H * W
        self.observation_space = spaces.Box(low=PAD_VALUE, high=N_COLORS - 1,
                                            shape=(obs_shape_flat,), dtype=np.int8)

        # State variables
        self.canvas = np.full((H, W), -1, dtype=np.int8)   # -1 = unpainted
        self.generated_input = None # The input grid generated by re-arc for this episode
        self.generated_output = None # The target output grid generated by re-arc
        self.original_train_pairs = [] # Loaded from the original ARC task file
        self.task_id = None
        self.cur_step = 0
        self.episode_len = H * W

    # ─── helpers ────────────────────────────────────────────
    def _load_original_task(self, task_id):
        """Loads the original train pairs for a given task ID."""
        task_file = ORIGINAL_ARC_TASKS.get(task_id)
        if not task_file:
            raise FileNotFoundError(f"Original ARC task file not found for ID: {task_id}")
        try:
            with open(task_file, 'r') as f:
                task_data = json.load(f)
            # Limit the number of training pairs loaded
            return task_data.get('train', [])[:MAX_TRAIN_PAIRS]
        except Exception as e:
            print(f"Error loading/parsing original task {task_id}: {e}")
            return [] # Return empty list on error

    def _generate_example_for_task(self, task_id):
        """Generates a new input/output pair using re-arc for the given task_id."""
        gen_fn_name = f"generate_{task_id}"
        if not hasattr(generators, gen_fn_name):
             # Fallback or error if generator doesn't exist (shouldn't happen with filtered TASK_IDS)
             print(f"Warning: re-arc generator {gen_fn_name} not found. Skipping.")
             return None # Indicate failure

        gen = getattr(generators, gen_fn_name)
        try:
            n = len(inspect.signature(gen).parameters)
            if n == 2:
                return gen(0.0, 1.0)
            if n == 1:
                return gen(self.rng.uniform(0.0, 1.0))
            return gen()
        except Exception as e:
            # Generator failed for this task ID
            print(f"Warning: Generator {gen_fn_name} failed: {e}. Trying another task.")
            return None # Indicate failure


    def _obs(self):
        """Constructs the multi-channel observation tensor."""
        # 1. Get current state (canvas overlayed on generated input)
        current_state = np.where(self.canvas >= 0, self.canvas, self.generated_input)

        # 2. Initialize observation tensor with padding value
        # Shape: (TOTAL_CHANNELS, H, W)
        obs_tensor = np.full((TOTAL_CHANNELS, H, W), PAD_VALUE, dtype=np.int8)

        # 3. Fill channel 0: current state
        obs_tensor[0, :, :] = current_state

        # 4. Fill channels for original train pairs
        num_pairs_to_use = min(len(self.original_train_pairs), MAX_TRAIN_PAIRS)
        for i in range(num_pairs_to_use):
            train_pair = self.original_train_pairs[i]
            # Pad original examples using the PAD_VALUE
            padded_train_input = pad_grid(train_pair['input'], fill=PAD_VALUE)
            padded_train_output = pad_grid(train_pair['output'], fill=PAD_VALUE)

            # Fill input channel (channels 1 to MAX_TRAIN_PAIRS)
            obs_tensor[1 + i, :, :] = padded_train_input
            # Fill output channel (channels MAX_TRAIN_PAIRS + 1 onwards)
            obs_tensor[1 + MAX_TRAIN_PAIRS + i, :, :] = padded_train_output

        # 5. Flatten and return
        return obs_tensor.flatten()

    # ─── Gym API ────────────────────────────────────────────
    def reset(self, *, seed=None, options=None):
        super().reset(seed=seed) # Ensure RandomState is seeded correctly if Gymnasium uses it
        if seed is not None:
             self.rng.seed(seed) # Also seed the internal random generator

        self.cur_step = 0
        generated_example = None

        # Loop until we successfully load a task and generate an example
        while generated_example is None:
            # 1. Select a valid ARC task ID that has both original data and a generator
            self.task_id = self.rng.choice(TASK_IDS)

            # 2. Load original training examples for this task
            self.original_train_pairs = self._load_original_task(self.task_id)
            if not self.original_train_pairs: # Skip if loading failed
                 print(f"Failed to load original examples for {self.task_id}, trying another task.")
                 continue

            # 3. Generate a new example using the re-arc generator for this task
            generated_example = self._generate_example_for_task(self.task_id)
            # Loop continues if generator failed (returned None)

        # 4. Set up the environment state using the generated example
        # Pad generated example using 0 (background color)
        self.generated_input = pad_grid(generated_example["input"], fill=0)
        self.generated_output = pad_grid(generated_example["output"], fill=0)

        # 5. Clear the canvas
        self.canvas.fill(-1) # -1 indicates unpainted

        # 6. Get initial observation
        initial_obs = self._obs()
        info = {"task_id": self.task_id, "num_train_pairs": len(self.original_train_pairs)}
        # print(f"[Env Reset] Task: {self.task_id}, Num Train Pairs: {len(self.original_train_pairs)}") # Optional debug print
        return initial_obs, info

    def step(self, action):
        # Ensure action components are integers
        try:
            r, c, color = map(int, action)
        except (ValueError, TypeError):
             print(f"Warning: Received invalid action format: {action}. Using (0,0,0).")
             r, c, color = 0, 0, 0 # Default action on error

        # Clip action components to valid ranges
        r = np.clip(r, 0, H - 1)
        c = np.clip(c, 0, W - 1)
        color = np.clip(color, 0, N_COLORS - 1) # Clip color to valid palette

        # --- Painting Logic ---
        # Only paint if the canvas cell is currently unpainted (-1)
        painted_this_step = False
        if self.canvas[r, c] == -1:
            self.canvas[r, c] = color
            painted_this_step = True

        # --- Reward Calculation ---
        # Reward is based on the color placed vs the *generated* ground truth
        # Only give reward if a paint action occurred *and* it was the first paint for that cell
        reward = 0.0
        pixel_correct = 0 # 0: incorrect/no action, 1: correct
        if painted_this_step:
            if color == self.generated_output[r, c]:
                reward = 1.0  # Correct color placed on first try
                pixel_correct = 1
            else:
                reward = -0.2 # Incorrect color placed on first try

        # --- Episode Termination ---
        self.cur_step += 1
        terminated = self.cur_step >= self.episode_len

        # Add bonus reward for exact match on termination
        final_board = None
        if terminated:
            final_board = np.where(self.canvas >= 0, self.canvas, self.generated_input)
            exact_match = int(np.array_equal(final_board, self.generated_output))
            reward += 10.0 * exact_match
            # print(f"[Env Terminated] Task: {self.task_id}, Final Reward: {reward:.2f}, Exact Match: {exact_match}") # Optional debug

        # --- Logging ---
        # Avoid excessive printing in step, maybe log less often or only on termination/high reward
        # print(f"[Env] step={self.cur_step:03d}/{self.episode_len} task={self.task_id} "
        #       f"action=({r},{c},{color}) painted={painted_this_step} "
        #       f"correct={pixel_correct if painted_this_step else 'N/A'} reward={reward:+.1f}")

        # --- Return Values ---
        # Get next observation if not terminated
        next_obs = None if terminated else self._obs()
        # Info dict
        info = {
            "task_id": self.task_id,
            "pixel_correct": pixel_correct if painted_this_step else 0, # Only relevant if painted
            "action_taken": (r, c, color),
            "painted_cell": painted_this_step,
        }
        if terminated:
            info["final_exact_match"] = exact_match

        # Return: observation, reward, terminated, truncated, info
        return next_obs, reward, terminated, False, info # Assuming no truncation